version: "3.1"

services:
  ts3-dialabot:
    build: .
    image: frebib/ts3-dialabot
    container_name: ts3-dialabot
    restart: always
    tty: true     # Allows systemd to log to console
    cap_add: 
      - SYS_NICE  # Required so pulseaudio starts correctly
    ports:
      - 5900:5900 # For accessing VNC for maintenence
    tmpfs:
      - /run
      - /tmp
    security_opt:
      - seccomp:unconfined
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - ./ts3client:/home/teamspeak/.ts3client:rw
    privileged: true
    stdin_open: true # docker run -i
    tty: true        # docker run -t

# vim: et sw=2
